### PR TITLE
Added 2 major glitches to the logic.

### PR DESCRIPTION
**Pull request by emerald000**
Walk on Water to access the Waterfall of Wishing and Fake Powder to access the Mad Batter item.

### CODE REVIEW

**Comment by pickfifteen** [comment]
How feasible are these to perform? Any videos of them around? My main concern here is I don't want to mark things as glitchavailable if the glitch required is out the realms of feasibility for the sort of runner who is still using an item tracker. Dark rooms are about the upper limit of how far I want things to stretch. Basically, if someone new-ish saw the dark green and came into chat asking how to get it, would it be able to be explained to them or would the answer be "you're probably not capable of doing it"?

**Comment by emerald000** [comment]
The Powderless Powder video: https://www.youtube.com/watch?v=i5M8LRlN9iQ. Basically you use Somaria when out of magic, then switch to mushroom and use it. Some good programming later you get the item. It might take a couple of tries to get the rhythm down, but it is pretty easy.

The Walk on Water glitch is an alternative way to Fake Flippers. If you dash on a corner of a hole then jump into the water, you'll walk on it instead. The second part of the Fake Flippers tutorial by superSKUJ explains how it works (https://youtu.be/D6zkcrc9PwM?t=590).

**Comment by pickfifteen** [comment]
I don't totally get the first, but if you're confident it'd be teachable to a new-ish player who asked in chat, I'm fine with it.

With the second, I assume that's a typo in the code change and it should be boots? That also seems fine.

**Comment by emerald000** [comment]
*facepalm* Yes, that's boots.

And yeah, the first one is weird. But it's pretty easy to pull off, even if it doesn't make any sense.

**Comment by pickfifteen** [comment]
Cool, if you can just check in a fix for that I'll get this merged and pushed out to prod.

**Comment by emerald000** [comment]
Fixed that.
"No need to test the new logic. The code is so simple. There couldn't possibly be an error in it." —Past me

**Comment by pickfifteen** [comment]
Thanks!

**Pull request merged**
