### PR TITLE
Add basic support for keysanity tracking

### PR DESCRIPTION
**Pull request by Carouelle**
It's still not entirely clear that the big key and small keys will appear if you click on the bottom part of the boss icon. This also comes at the sacrifice of the chest tracker. 

There are matches from the current keysanity tournament that are restreamed elsewhere than Speedgaming channels, and they use this tracker. However, it is lacking key tracking. My main goal with this PR is to provide a keysanity support to these channels.

If you want to test it out: https://lttp-tracker-f0591.firebaseapp.com

### CODE REVIEW

**Comment by pickfifteen** [comment]
Looks fantastic, I'll merge and work on getting this up on the main site. Thanks for the PR!

**Comment by Carouelle** [comment]
Thank you! Can you also mention my Discord/Twitch name "Ninban" in place of my Github name? Just to get proper credit.

**Comment by emerald000** [comment]
Is there some way to have the chest tracker along with the keys? I really like my chest counts and would rather not have to choose between both.

Also: any plan to update the logic for keysanity?

**Comment by pickfifteen** [comment]
To have multiple things in the same box probably requires a smarter treatment of how subitems are displayed; i.e. rather than having them in a fixed position, they fill in the existing space depending on what is or is not used. Which would probably go along with the general revamp of the grid html layer.

As far as actually doing the dev work to put that into place or any other updates including logic, I have no plans to do so myself--and as always don't really have the domain knowledge to do the logic updates correctly anyway--but will continue to review PRs and accept those that contribute and don't harm the primary goal of the tracker, to assist new players.

**Comment by Carouelle** [comment]
I'd love to be able to replace the dungeon label with the chest tracker personnally. But then we don't have anymore space to click on the boss icons for MM and TR, so I don't know what's the best way to tackle this issue.

I do plan to propose a logic update for keysanity down the road. No key tracking was my major roadblock for this, but now that I've decided to do it (clearly inspired by the way Speedgaming's tracker presents it), I want to get started on that soon.

**Pull request merged**
