### PR TITLE
Added images and behavior for distinction between aga 1 and 2 in the item/boss grid

### PR DESCRIPTION
**Pull request by epiblitikos**
didn't change the item light-up behavior because beating aga 2 does place on you on the pyramid (same as aga 1)

### CODE REVIEW

**Comment by epiblitikos** [comment]
If you want to see it without updating yours, check https://lttp-tracker-epi.firebaseapp.com/test and setup a room.

**Comment by pickfifteen** [comment]
Interesting; so if I'm getting the idea of this correctly: state zero is neither aga defeated, state one is aga 1 defeated only, state two is aga 2 defeated only, state three is both agas defeated?

Has there been a change or a new mode that is causing people to still use the chest tracker after getting to Ganon's Tower? In watching tracker usage, it seems to me 99% of people stop tracking items or at least certainly chests at that point, and we don't even have a indicator for how many items are in GT at all; I've only ever seen one tracker that did.

**Comment by emerald000** [comment]
In entrance randomizer, you can choose to have Ganon's Tower shuffled into a random location. So sometimes you have to complete it earlier to unlock the pyramid entrance.

**Comment by pickfifteen** [comment]
Gotcha. I'll admit I had just assumed this tracker wasn't usable for ER at all, considering how many location assumptions it is making everywhere--are ER runners making use of it? Are there any other quick fixes that might make it more usable without a full rebuild?

As far as this PR goes, I feel like having the defeated Aga sprite on each of states 1-3, with the distinction being only the lit or unlit numbers, would be a little more clear; it would allow this added functionality for ER folks to exist with a more minor impact on the current look-and-feel for the majority of runners who will only ever be using that field to track aga 1. Thoughts?

An alternative would be to leave this sprite for Aga 1 as is and just add a new 'dungeon' item for GT/Aga2, which would also allow tracking the number of items allowed, and change all the checks for aga to check for either normal aga1 or this new dungeon completed; but as I'm not familiar with ER, I don't know whether this would be useful or not.

**Comment by epiblitikos** [comment]
>  state zero is neither aga defeated, state one is aga 1 defeated only, state two is aga 2 defeated only, state three is both agas defeated

That's correct. And I would be okay with changing states 1-3 to have a dead aga with appropriate number colors.

As far as use for ER runners: my main use case/reason for the change was for use as a tracker during ER races, where the location info (and the "chests left in X" info) is omitted from display. The ER version of the tracker is basically a project/epic unto itself, perhaps best implemented as a mode or separate app entirely.

For item rando, the change definitely holds less value in general, where your suggestion of implementing a full dungeon treatment of GT/Aga2 does make more sense--even for ER runners. If you'd rather hold off on any ER-related changes until more can be rolled out, I totally understand.

**Comment by pickfifteen** [comment]
I'm happy to incrementally add any changes that help out ER folks without having too much impact on mainline; adding a GT dungeon wouldn't be an issue since each dungeon can just be removed from the display. Since I don't know and it would be needed to implement that, do you know how many items are in GT?

As far as this change, if you can update the images as discussed, I'll be happy to merge it and update the main website this evening.

**Comment by epiblitikos** [comment]
Sounds good! Yeah I don't want to add anything that actually results in worse UX for the intended and realized purpose.

I'll have to get the images changed tonight--at work currently. And I'll have to check the number for GT. I forget how many keys-in-chests/bonks are in that dungeon. 

I'll circle back on both when I get home.

**Comment by epiblitikos** [comment]
Commit added, and looks like 20 items in Ganon's Tower, coming from

* 27 locations
* 3 have to be map, compass, big key
* 4 keys in rando locations (bonk torch, tile room, fire snake room, pre-moldorm 2 chest)

**Comment by pickfifteen** [comment]
Thanks for checking in on that! The main website has also been updated.

**Comment by epiblitikos** [comment]
Sure thing man! I'm trying my hand at adding the dungeon now. Cheers!

**Pull request merged**
